### ISSUE TITLE
WebToken time to live should be configurable

### ISSUE THREAD

**Issue by henrikbjorn** [flint/Antenna#4]
`UsernamePasswordAuthenticator` should have a way to control the time to live for a `WebToken`. Currently it is always 7 days.

**Comment by kbond** [comment]
Is this possible now?

**Comment by jdreesen** [comment]
According to the [release notes of the v1.2.0 tag](https://github.com/flint/Antenna/releases/tag/1.2.0), yes.

**Comment by kbond** [comment]
Ah, I see that it is configurable in the library but not the bundle.

**Comment by henrikbjorn** [comment]
feel free to open a pr for the bundle :)

**Comment by henrikbjorn** [comment]
@kbond done in https://github.com/flint/AntennaBundle/releases/tag/1.1.0

**Comment by kbond** [comment]
Nice, thanks @henrikbjorn
